version: '3.7'

services:

  webapp:
    container_name: webapp
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  couchdb:
    container_name: couchdb
    image: couchdb:3.0
    ports:
        - 5984:5984
    volumes:
        - couch_data:/opt/couchdb/data
    env_file:
        - .env

volumes:
    couch_data:
