version: '3.7'

services:

  webapp:
    container_name: webapp
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

#   webapp1:
#     image: nginx
#     ports:
#         - 3001:80
#     volumes:
#         - "$PWD/build:/usr/share/nginx/html:ro"

#   webapp2:
#     image: nginx
#     ports:
#         - 3002:80
#     volumes:
#         - "$PWD/build:/usr/share/nginx/html:ro"

  couchdb:
    container_name: couchdb
    image: couchdb:3.0
    ports:
        - 5984:5984
    volumes:
        - couch_data:/opt/couchdb/data
    env_file:
        - .env

volumes:
    couch_data:
