version: '3.7'

services:

  amplify-app:
    container_name: amplify-app
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_MODE=amplify
  
  pouchdb-app:
    container_name: pouchdb-app
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COUCHDB_HOST=http://couchdb:5984

  couchdb:
    container_name: couchdb
    image: couchdb:3.0
    ports:
        - 5984:5984
    volumes:
        - couch_data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password

volumes:
    couch_data:
