"""empty message
# flake8: noqa
Revision ID: 2d5d6f7a5330
Revises: b0ecefa97eda
Create Date: 2020-11-20 16:25:22.121061
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2d5d6f7a5330'
down_revision = 'b0ecefa97eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index('idx_site_location', table_name='site')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_site_location', 'site', ['location'], unique=False)
    op.alter_column('site', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
