/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
  aws_project_region: process.env.REACT_APP_AMPLIFY_REGION,
  aws_appsync_graphqlEndpoint: process.env.REACT_APP_AMPLIFY_EP,
  aws_appsync_region: process.env.REACT_APP_AMPLIFY_REGION,
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: process.env.REACT_APP_AMPLIFY_KEY,
}
export default awsmobile
